# config.py

IMG_SIZE = 224
PATCH_SIZE = 16
IN_C = 3
NUM_CLASSES = 1000
EMBED_DIM = 768
DEPTH = 12
NUM_HEADS = 12
MLP_RATIO = 4.0
QKV_BIAS = True
QK_SCALE = None
REPRESENTATION_SIZE = None
DROP_RATIO = 0.0
ATTN_DROP_RATIO = 0.0
DROP_PATH_RATIO = 0.0
